name: Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Go 语言示例，如需其他语言，请修改安装和编译命令
      - name: Set up Go
        uses: actions/setup-go@v5
        if: ${{ env.LANGUAGE == 'go' || steps.detect.outputs.language == 'go' }}
        with:
          go-version: '1.22'

      - name: Build Binary
        run: |
          mkdir -p dist
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            GOOS=linux GOARCH=amd64 go build -o dist/clean-dns-linux-amd64
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            GOOS=windows GOARCH=amd64 go build -o dist/clean-dns-windows-amd64.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            GOOS=darwin GOARCH=amd64 go build -o dist/clean-dns-darwin-amd64
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
